version: '3'

services:
  db:
    container_name: mysql8-bun
    platform: linux/x86_64
    image: mysql:8.0.22
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '23306:3306'
